version: '3.9'

services:
  db:
    image: postgres:15.3
    container_name: nestjs_db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    restart: always
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./src:/home/backend_app/src
      - node_modules:/home/backend_app/node_modules
    ports:
      - '3000:3000'

volumes:
  postgres_data:
  node_modules: